### ISSUE TITLE
Steering the fan via actions

### ISSUE THREAD

**Issue by knulle2024** [hmn/siku-integration#102]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/hmn/siku-integration/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'm running the integration with oxxify smart 50 fans, and the connection to the fans was easily made, so first of all thx a lot for this great integration!
My problem (and most likely I'm the problem myself being new to home assistant):
I'm not able to adress the fans via code. The only solution I found is "on" "off" and "toggle". For my automation I would need full access to the controls that are shown (Level 1 2 3, boost , party, auto on/off...). as it is possible to control these features "manually", obviously the required commands are known.

### Describe the solution you'd like

A documentation how to access the additional control features via code/ automation

### Describe alternatives you've considered

No alternatives

### Additional context

not required I guess

**Comment by rostwolke** [comment]
I had the exact same problem a couple of hours ago. When I checked the source code I noticed that the fan speed can be indeed set (sorry, my HA is in German):
![grafik](https://github.com/user-attachments/assets/311cd49d-e4da-4fe1-9af7-0443e9501728)

If you directly want to add a button without opening the entity you can give a script a try. Once mine is done I will share it here.

**Comment by knulle2024** [comment]
Great! Made my day... Thx a lot! Searching for "Lüfter" in automations did the trick. (My HA is also in German...)

**Comment by rostwolke** [comment]
Amazing. Here as promised my card:

```
entity: fan.fan_dennis
type: custom:multiple-entity-row
attribute: percentage
name: Fan speed
show_state: false
entities:
  - icon: mdi:fan-off
    tap_action:
      action: call-service
      service: fan.set_percentage
      service_data:
        entity_id: fan.fan_dennis
        percentage: 0
  - icon: mdi:fan-speed-1
    tap_action:
      action: call-service
      service: fan.set_percentage
      service_data:
        entity_id: fan.fan_dennis
        percentage: 33
  - icon: mdi:fan-speed-2
    tap_action:
      action: call-service
      service: fan.set_percentage
      service_data:
        entity_id: fan.fan_dennis
        percentage: 66
  - icon: mdi:fan-speed-3
    tap_action:
      action: call-service
      service: fan.set_percentage
      service_data:
        entity_id: fan.fan_dennis
        percentage: 100
card_mod:
  style: >
    :host .entity:nth-child({{ (state_attr('fan.fan_dennis', 'percentage') / 33
    + 1)|int }}) .icon-small {
      color: var(--rgb-state-default-color);
    }
```

It will only work properly if you installed the two following plugins (available on HACS):

- card-mod
- multiple-entity-row

In the end it will look like this which in my opinion is far better to control:
![grafik](https://github.com/user-attachments/assets/cb638e64-e49c-4c39-9fe9-1b58ebe25eeb)
