### ISSUE TITLE
V2: Set Sleep or Party Mode via HA Automation

### ISSUE THREAD

**Issue by victori3d** [hmn/siku-integration#45]
**Is your feature request related to a problem? Please describe.**
For the V2 of Siku/Oxxify, you currently can only set the following settings manually like speed or sleep/party mode. I would like to automate when the device should go into sleep/party mode.

**Describe the solution you'd like**
I would like to set the Sleep or Party Mode depending on certain settings. Currently, it is not possible to set the Sleep/Party Mode as a state.

**Describe alternatives you've considered**
I need to manually set the Sleep or Party Mode.

**Comment by hmn** [comment]
I don't think I undestand what you are requesting?

As far as I know it is possible to trigger a mode change in automations

```yaml
service: fan.set_preset_mode
data:
  preset_mode: party
target:
  entity_id: fan.living_room_fan
```
